### ISSUE TITLE
CSS Issue: Link and Tag Text Overflowing Card Boundaries

### ISSUE THREAD

**Issue by Az779** [decaf-dev/obsidian-vault-explorer#318]
<img src="https://github.com/user-attachments/assets/7ae29f06-f7f4-4c45-89ae-1655ad1ac480" width="300" />

See image above, long links and tags cause text to overflow the card boundaries in the Grid View. ( I modified the size of the card)
The following CSS could be applied to fix this:

```css
.vault-explorer-grid-card__url,
.vault-explorer-tag.vault-explorer-tag--unstyled{
  overflow: hidden;
}
```

after:
<img src="https://github.com/user-attachments/assets/c68ae9f1-a053-49a8-bde1-ac7933396aa2" width="300" />
