### ISSUE TITLE
4 Ideas: Preferred View, Mansory Grid  for Images, Preflight for Links, Load more

### ISSUE THREAD

**Issue by cnichte** [decaf-dev/obsidian-vault-explorer#370]
Hi, love your Plugin! Great Concept and a missing link in Obsidan, that has the potential to replace several plugins.

1. Preferred View-Option in Filter-Settings like so:

![ScreenFloat Bildschirmfoto von Obsidian am 02_12_2024, 20_01_09](https://github.com/user-attachments/assets/b469819b-f09a-4b7d-b068-a2484bfae434)

2. A Mansory Grid Layout for Images. Perhaps with Fullscreen Lightbox a Navigation previous / next.

![ScreenFloat Bildschirmfoto von Obsidian am 02_12_2024, 20_04_11](https://github.com/user-attachments/assets/28a10721-288f-48c5-9488-9180c6ec6119)

3. Preflight for Links, like so - like  the internal links in Obsidian:

![ScreenFloat Bildschirmfoto von Obsidian am 02_12_2024, 20_06_48](https://github.com/user-attachments/assets/aa2631b0-4dd1-4d40-9bd5-5dedf287c50f)

4. Optional a modern `Load more` Button instead of the Traditional Page Switch.

**Comment by Azona77** [comment]
I also hope to have a more free Mansory layout, like the note gallery plugin;
I found a case where a 3-column Mansory layout can be realized through pure CSS. I hope it can help.
But more than 4 columns will require plug-in modification. 

<div align=center>
<img src="https://github.com/user-attachments/assets/cebb98d4-0973-491d-ad86-65efab16481b" width="200px" style="margin-right:auto; margin-left:auto">
</div>

```css
.vault-explorer-grid-card__url{
  display: none;
}
.vault-explorer-grid-card__footer{
  display: none;
}
/* Hide lower half of the card without tags*/
.vault-explorer-grid-card__footer:has(:empty){
  padding-top: 0!important;
  padding-bottom: 0!important;
}
/* Cards without covers - header enlargement */
.vault-explorer-grid-card:has(div.vault-explorer-grid-card__image) .vault-explorer-grid-card__title,
.vault-explorer-grid-card:not(:has(div.vault-explorer-grid-card__cover > *)) .vault-explorer-grid-card__title{
  font-size: x-large;
}
.vault-explorer-icon.vault-explorer-icon--xs{
  display: none!important;
}
.vault-explorer-grid-view__container.svelte-q9ur25{
  row-gap: .25rem;
  column-gap: .25rem;
  justify-content: center;
}
.vault-explorer-grid-card {
  position: relative!important;
  width: 150px!important;
}
/*
;-----------------------------------------------------------------------------------
; Code snippet adapted from:
    ;https://codepen.io/collection/XPjvPP/
*/

.vault-explorer-grid-view__container.svelte-q9ur25 {
  display: flex;
  flex-flow: column wrap;
  align-content: space-between;
  justify-content: flex-start;
  /* Your container needs a fixed height, and it 
   * needs to be taller than your tallest column. */
  height: 30000px;
  margin: 0px auto;
  counter-reset: items;
}

/* View serial number */
/* .vault-explorer-grid-card.vault-explorer-grid-card--interactive.svelte-uq88l3::before {
  counter-increment: items;
  content: counter(items);
} */

/* Re-order items into 3 rows */
.vault-explorer-grid-card:nth-child(3n+1) { order: 1; }
.vault-explorer-grid-card:nth-child(3n+2) { order: 2; }
.vault-explorer-grid-card:nth-child(3n)   { order: 3; }

/* Force new columns */
.vault-explorer-grid-view__container::before,
.vault-explorer-grid-view__container::after {
  content: "";
  flex-basis: 100%;
  width: 0;
  order: 2;
}

.vault-explorer-grid-card__cover {
  width: 150px!important;
  height: fit-content!important;
}
.vault-explorer-grid-card__image {
  width: 150px!important;
  height: fit-content!important;
}

.vault-explorer-stack,
.vault-explorer-tag,
.vault-explorer-wrap{
  overflow: hidden;
}
.vault-explorer-grid-card__title-text{
  text-overflow:clip!important;
  white-space: normal!important;
  max-height: 4em;
}

```
